name: X Environment setup

on:
  workflow_call:
    outputs:
      gh-org:
        description: "GitHub Organization"
        value: ${{ jobs.env.outputs.gh-org }}
      mvn-releases-url:
        description: "Maven Releases URL"
        value: ${{ jobs.env.outputs.mvn-releases-url }}
      mvn-snapshots-url:
        description: "Maven Snapshots URL"
        value: ${{ jobs.env.outputs.mvn-snapshots-url }}
      quay-org:
        description: "Quay Organization"
        value: ${{ jobs.env.outputs.quay-org }}
      docker-org:
        description: "Docker Organization"
        value: ${{ jobs.env.outputs.docker-org }}
      community-operators-org:
        description: "Community operators organization name"
        value: ${{ jobs.env.outputs.community-operators-org }}
      prod-operators-org:
        description: "Product operators organization name"
        value: ${{ jobs.env.outputs.prod-operators-org }}
      operatorhub-author-email:
        description: "Author's EMAIL who sends PRs to operators repositories"
        value: ${{ jobs.env.outputs.operatorhub-author-email }}
      operatorhub-author-name:
        description: "Author's NAME who sends PRs to operators repositories"
        value: ${{ jobs.env.outputs.operatorhub-author-name }}

defaults:
  run:
    shell: bash

jobs:
  env:
    runs-on: ubuntu-latest
    outputs:
      gh-org: ${{ env.gh-org }}
      mvn-releases-url: ${{ env.mvn-releases-url }}
      mvn-snapshots-url: ${{ env.mvn-snapshots-url }}
      quay-org: ${{ env.quay-org }}
      docker-org: ${{ env.docker-org }}
      community-operators-org: ${{ env.community-operators-org }}
      prod-operators-org: ${{ env.prod-operators-org }}
      operatorhub-author-email: ${{ env.operatorhub-author-email }}
      operatorhub-author-name: ${{ env.operatorhub-author-name }}
    steps:
      - uses: actions/checkout@v3
      - id: load-env
        run: |
          cat .github/env/${{ github.repository_owner }} | sed -r '/^\s*$/d' >> $GITHUB_ENV
