name: X Environment setup

on:
  workflow_call:
    outputs:
      gh-org:
        description: "GitHub Organization"
        value: ${{ jobs.env.outputs.gh-org }}
      mvn-releases-url:
        description: "Maven Releases URL"
        value: ${{ jobs.env.outputs.mvn-releases-url }}
      mvn-snapshots-url:
        description: "Maven Snapshots URL"
        value: ${{ jobs.env.outputs.mvn-snapshots-url }}
      quay-org:
        description: "Quay Organization"
        value: ${{ jobs.env.outputs.quay-org }}
      operator-publish-repo-org:
        description: "Target organization of fork for pushing necessary changes"
        value: ${{ jobs.env.outputs.operator-publish-repo-org }}
      docker-org:
        description: "Docker Organization"
        value: ${{ jobs.env.outputs.docker-org }}
      community-operators-repo:
        description: "Community operators repository"
        value: ${{ jobs.env.outputs.community-operators-repo }}
      prod-operators-repo:
        description: "Product operators repository"
        value: ${{ jobs.env.outputs.prod-operators-repo }}

defaults:
  run:
    shell: bash

jobs:
  env:
    runs-on: ubuntu-latest
    outputs:
      gh-org: ${{ env.gh-org }}
      mvn-releases-url: ${{ env.mvn-releases-url }}
      mvn-snapshots-url: ${{ env.mvn-snapshots-url }}
      quay-org: ${{ env.quay-org }}
      operator-publish-repo-org: ${{ env.operator-publish-repo-org }}
      docker-org: ${{ env.docker-org }}
      community-operators-repo: ${{ env.community-operators-repo }}
      prod-operators-repo: ${{ env.prod-operators-repo }}
    steps:
      - uses: actions/checkout@v3
      - id: load-env
        run: |
          cat .github/env/${{ github.repository_owner }} | sed -r '/^\s*$/d' >> $GITHUB_ENV
